language: c

addons:
  apt:
    packages:
     - libcap-dev
     - libkrb5-dev
     - libpam0g-dev
     - libssl-dev
     - libx11-dev
     - libxdamage-dev
     - libxext-dev
     - libxfixes-dev
     - libxi-dev
     - libxrandr-dev
     - libxrender-dev
     - libxtst-dev

script: make
